spring.application.name=chronos


# ===============================
# = Spring Datasource (Postgres)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Chronos
spring.datasource.username=postgres
spring.datasource.password=Chaitanya@26
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = Hibernate / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=create-drop
# options: none | validate | update | create | create-drop

spring.jpa.show-sql=true
spring.jpa.generate-ddl = true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = Server
# ===============================
server.port=8181

#Spring Swagger UI Properties
springdoc.swagger-ui.path=/swagger-ui

api.prefix = /chronos